AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/*.gemfile'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 112

Metrics/MethodLength:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - '*.gemspec'

Layout/LineLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
