cache: bundler
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - ruby-head
  - truffleruby-head
gemfile:
  - gemfiles/standalone.gemfile
  - gemfiles/openssl.gemfile
  - gemfiles/rbnacl.gemfile
script: 
  - bundle exec rspec
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - gem install bundler
matrix:
  fast_finish: true
  includes:
    - rvm: 2.7
      name: "Run Code Climate"
      after_script:
        - bundle exec codeclimate-test-reporter
  allow_failures:
    - rvm: 2.2
    - rvm: 2.1
    - rvm: ruby-head
    - rvm: truffleruby-head
