# frozen_string_literal: true

if defined?(RbNaCl)
  RSpec.describe ::JWT::Algos::HmacRbNaCl do
    let(:data) { 'this_is_the_string_to_be_signed' }
    let(:key) { 'the secret key' }

    describe '.verify' do
      context 'when signature is generated with OpenSSL' do
        let(:signature) { ::JWT::Algos::Hmac.sign(::JWT::Signature::ToSign.new('HS256', data, key)) }
        it 'verifies the signature' do
          expect(described_class.verify(::JWT::Signature::ToVerify.new('HS256', key, data, signature))).to eq(true)
        end
      end
    end

    describe '.sign' do
      context 'when signature is generated by RbNaCl' do
        let(:signature) { described_class.sign(::JWT::Signature::ToSign.new('HS256', data, key)) }
        it 'can verify the signature with OpenSSL' do
          expect(::JWT::Algos::Hmac.verify(::JWT::Signature::ToVerify.new('HS256', key, data, signature))).to eq(true)
        end
      end
    end
  end
end
