---
name: ci
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: "Ruby {{ matrix.ruby }}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - 2.3
        - 2.4
        - 2.5
        - 2.6
        - 2.7
        experimental: [false]
        include:
          - ruby: "ruby-head"
            experimental: true
          - ruby: "truffleruby-head"
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec
