---
name: test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: RuboCop
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop
  test:
    name: ${{ matrix.os }} - Ruby ${{ matrix.ruby }} - ${{ matrix.gemfile }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        gemfile:
          - gemfiles/standalone.gemfile
          - gemfiles/openssl.gemfile
          - gemfiles/rbnacl.gemfile
          - gemfiles/rbnacl-pre-6.gemfile
        experimental: [false]
        include:
          - os: ubuntu-22.04
            ruby: "3.1"
            gemfile: 'gemfiles/standalone.gemfile'
            experimental: false
          - os: ubuntu-20.04
            ruby: "truffleruby-head"
            gemfile: 'gemfiles/standalone.gemfile'
            experimental: true
          - os: ubuntu-22.04
            ruby: "head"
            gemfile: 'gemfiles/standalone.gemfile'
            experimental: true
    continue-on-error: ${{ matrix.experimental }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3

      - name: Install libsodium
        run: |
          sudo apt-get update -q
          sudo apt-get install libsodium-dev -y

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec

      - name: Upload test coverage folder for later reporting
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: ${{github.workspace}}/coverage-*/coverage.json
          retention-days: 1

  coverage:
    name: Report coverage to Code Climate
    runs-on: ubuntu-20.04
    needs: test
    if: success() && github.ref == 'refs/heads/main'
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - uses: actions/checkout@v3

      - name: Download coverage reports from the test job
        uses: actions/download-artifact@v3
        with:
          name: coverage-reports

      - uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageLocations: "coverage-*/coverage.json:simplecov"

  smoke:
    name: Built GEM smoke test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Build GEM
        run: gem build
      - name: Install built GEM
        run: gem install jwt-*.gem
      - name: Run test
        run: bin/smoke.rb
